alert("Bienvenidos a taller tecnologico II")
console.log("esto que estoy escribiendo se vera en la concola de logica:js:2 HTML")
console.log("esta va ser la tercera version")
console.log("este cambio ira hasta remoto")
console.log("se agrega cambios en ramas pruebas")
